modLoader="javafml"
loaderVersion="[${loader_version},)"
license="All Rights Reserved unless otherwise explicitly stated"

[[mods]]
modId="beyond_earth"
version="${mod_version}"
displayName="Beyond Earth"
displayURL="https://www.curseforge.com/minecraft/mc-mods/beyond-earth"
issueTrackerURL = "https://github.com/MrScautHD/Beyond-Earth/issues"
logoFile="logo.png"
authors="MrScautHD, St0x0ef and other contributor"
description='''Fly to Other Planets and Beyond!'''

[[dependencies.beyond_earth]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mc_version}]"
    ordering="NONE"
    side="BOTH"

[[dependencies.beyond_earth]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},]"
    ordering="NONE"
    side="BOTH"